name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: project-1-400619
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/project-1-400619/project-one:${{ github.run_number }} .
          docker push gcr.io/project-1-400619/project-one:${{ github.run_number }}

  depoly:
  
      runs-on: ubuntu-latest
      needs: build
        
      steps: 

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: project-1-400619
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true
      
      - name: Set Kubectl Context
        run: gcloud container clusters get-credentials google-test-1 --zone us-central1 --project project-1-400619 

      - name: Deploy to GKE
        run: |
          DOCKER_IMAGE=gcr.io/project-1-400619/project-one:${{ github.run_number }}
          docker pull $DOCKER_IMAGE
          gcloud auth configure-docker use-central1-docker.pkg.dev
          kubectl apply -f - kubectl rollout status deployment/$project-one-deployment
          kubectl apply -f service.yaml
        #kubectl apply -f deployment.yaml
          
        #kubectl rollout  restart  -f deployment.yaml
         

                
          
